[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assets/assetlinks.json"
  status = 200
  force = true

[[redirects]]
  from = "https://layl.app/layl"
  to = "https://layl.app"
  status = 301
  force = true